so ~/dotfiles/vim/plugin.vim
so ~/dotfiles/vim/color.vim
so ~/dotfiles/vim/keymap.vim
so ~/dotfiles/vim/others.vim
so ~/dotfiles/vim/vim-coc.vim
so ~/dotfiles/vim/snippets.vim
so ~/dotfiles/vim/airline.vim
so ~/dotfiles/vim/clang-format.vim
so ~/dotfiles/vim/js-beautifier.vim
so ~/dotfiles/vim/copy-paste.vim
